// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// extract_tracts_flare_cpp
void extract_tracts_flare_cpp(std::string vcf_path, int num_ancs, std::string out_prefix, CharacterVector formats, int chunk_size, Function gds_append_fn);
RcppExport SEXP _tlstractor_extract_tracts_flare_cpp(SEXP vcf_pathSEXP, SEXP num_ancsSEXP, SEXP out_prefixSEXP, SEXP formatsSEXP, SEXP chunk_sizeSEXP, SEXP gds_append_fnSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type vcf_path(vcf_pathSEXP);
    Rcpp::traits::input_parameter< int >::type num_ancs(num_ancsSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_prefix(out_prefixSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type formats(formatsSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< Function >::type gds_append_fn(gds_append_fnSEXP);
    extract_tracts_flare_cpp(vcf_path, num_ancs, out_prefix, formats, chunk_size, gds_append_fn);
    return R_NilValue;
END_RCPP
}
// extract_tracts_cpp
void extract_tracts_cpp(std::string vcf_path, std::string msp_path, int num_ancs, std::string out_prefix, CharacterVector formats, int chunk_size, Function gds_append_fn);
RcppExport SEXP _tlstractor_extract_tracts_cpp(SEXP vcf_pathSEXP, SEXP msp_pathSEXP, SEXP num_ancsSEXP, SEXP out_prefixSEXP, SEXP formatsSEXP, SEXP chunk_sizeSEXP, SEXP gds_append_fnSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type vcf_path(vcf_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type msp_path(msp_pathSEXP);
    Rcpp::traits::input_parameter< int >::type num_ancs(num_ancsSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_prefix(out_prefixSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type formats(formatsSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< Function >::type gds_append_fn(gds_append_fnSEXP);
    extract_tracts_cpp(vcf_path, msp_path, num_ancs, out_prefix, formats, chunk_size, gds_append_fn);
    return R_NilValue;
END_RCPP
}
// convert_tracts_txt_to_gds_cpp
void convert_tracts_txt_to_gds_cpp(CharacterVector dosage_files, CharacterVector hap_files, int nsamples, int chunk_size, Function gds_append_fn);
RcppExport SEXP _tlstractor_convert_tracts_txt_to_gds_cpp(SEXP dosage_filesSEXP, SEXP hap_filesSEXP, SEXP nsamplesSEXP, SEXP chunk_sizeSEXP, SEXP gds_append_fnSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type dosage_files(dosage_filesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type hap_files(hap_filesSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< Function >::type gds_append_fn(gds_append_fnSEXP);
    convert_tracts_txt_to_gds_cpp(dosage_files, hap_files, nsamples, chunk_size, gds_append_fn);
    return R_NilValue;
END_RCPP
}
// gds_to_txt_open_writer_cpp
SEXP gds_to_txt_open_writer_cpp(std::string out_path, bool gz);
RcppExport SEXP _tlstractor_gds_to_txt_open_writer_cpp(SEXP out_pathSEXP, SEXP gzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type out_path(out_pathSEXP);
    Rcpp::traits::input_parameter< bool >::type gz(gzSEXP);
    rcpp_result_gen = Rcpp::wrap(gds_to_txt_open_writer_cpp(out_path, gz));
    return rcpp_result_gen;
END_RCPP
}
// gds_to_txt_write_header_cpp
void gds_to_txt_write_header_cpp(SEXP writer_ptr, CharacterVector sample_ids);
RcppExport SEXP _tlstractor_gds_to_txt_write_header_cpp(SEXP writer_ptrSEXP, SEXP sample_idsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type writer_ptr(writer_ptrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sample_ids(sample_idsSEXP);
    gds_to_txt_write_header_cpp(writer_ptr, sample_ids);
    return R_NilValue;
END_RCPP
}
// gds_to_txt_append_chunk_cpp
void gds_to_txt_append_chunk_cpp(SEXP writer_ptr, CharacterVector chroms, IntegerVector pos, CharacterVector ids, CharacterVector refs, CharacterVector alts, NumericMatrix mat);
RcppExport SEXP _tlstractor_gds_to_txt_append_chunk_cpp(SEXP writer_ptrSEXP, SEXP chromsSEXP, SEXP posSEXP, SEXP idsSEXP, SEXP refsSEXP, SEXP altsSEXP, SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type writer_ptr(writer_ptrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type chroms(chromsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos(posSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type refs(refsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type alts(altsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    gds_to_txt_append_chunk_cpp(writer_ptr, chroms, pos, ids, refs, alts, mat);
    return R_NilValue;
END_RCPP
}
// gds_to_txt_close_writer_cpp
void gds_to_txt_close_writer_cpp(SEXP writer_ptr);
RcppExport SEXP _tlstractor_gds_to_txt_close_writer_cpp(SEXP writer_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type writer_ptr(writer_ptrSEXP);
    gds_to_txt_close_writer_cpp(writer_ptr);
    return R_NilValue;
END_RCPP
}
// merge_task_results_cpp
void merge_task_results_cpp(std::string output_path, std::string task_file_prefix, std::string task_file_suffix, int num_tasks);
RcppExport SEXP _tlstractor_merge_task_results_cpp(SEXP output_pathSEXP, SEXP task_file_prefixSEXP, SEXP task_file_suffixSEXP, SEXP num_tasksSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type output_path(output_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type task_file_prefix(task_file_prefixSEXP);
    Rcpp::traits::input_parameter< std::string >::type task_file_suffix(task_file_suffixSEXP);
    Rcpp::traits::input_parameter< int >::type num_tasks(num_tasksSEXP);
    merge_task_results_cpp(output_path, task_file_prefix, task_file_suffix, num_tasks);
    return R_NilValue;
END_RCPP
}
// tlstractor_linear_precompute
List tlstractor_linear_precompute(NumericVector y, NumericMatrix A, double tol_scale_rank);
RcppExport SEXP _tlstractor_tlstractor_linear_precompute(SEXP ySEXP, SEXP ASEXP, SEXP tol_scale_rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type tol_scale_rank(tol_scale_rankSEXP);
    rcpp_result_gen = Rcpp::wrap(tlstractor_linear_precompute(y, A, tol_scale_rank));
    return rcpp_result_gen;
END_RCPP
}
// fill_chunk_with_sumstats_softpass_linear
List fill_chunk_with_sumstats_softpass_linear(List dos_list, List hap_list, IntegerVector idx, NumericVector sumstats_beta, NumericVector sumstats_se, List precomp, List control, bool has_covar, bool cond_local, int num_ancs);
RcppExport SEXP _tlstractor_fill_chunk_with_sumstats_softpass_linear(SEXP dos_listSEXP, SEXP hap_listSEXP, SEXP idxSEXP, SEXP sumstats_betaSEXP, SEXP sumstats_seSEXP, SEXP precompSEXP, SEXP controlSEXP, SEXP has_covarSEXP, SEXP cond_localSEXP, SEXP num_ancsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dos_list(dos_listSEXP);
    Rcpp::traits::input_parameter< List >::type hap_list(hap_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sumstats_beta(sumstats_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sumstats_se(sumstats_seSEXP);
    Rcpp::traits::input_parameter< List >::type precomp(precompSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< bool >::type has_covar(has_covarSEXP);
    Rcpp::traits::input_parameter< bool >::type cond_local(cond_localSEXP);
    Rcpp::traits::input_parameter< int >::type num_ancs(num_ancsSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_chunk_with_sumstats_softpass_linear(dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, has_covar, cond_local, num_ancs));
    return rcpp_result_gen;
END_RCPP
}
// fill_chunk_with_sumstats_softfail_linear
List fill_chunk_with_sumstats_softfail_linear(List dos_list, List hap_list, IntegerVector idx, NumericVector sumstats_beta, NumericVector sumstats_se, List precomp, List control, bool has_covar, bool cond_local, int num_ancs);
RcppExport SEXP _tlstractor_fill_chunk_with_sumstats_softfail_linear(SEXP dos_listSEXP, SEXP hap_listSEXP, SEXP idxSEXP, SEXP sumstats_betaSEXP, SEXP sumstats_seSEXP, SEXP precompSEXP, SEXP controlSEXP, SEXP has_covarSEXP, SEXP cond_localSEXP, SEXP num_ancsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dos_list(dos_listSEXP);
    Rcpp::traits::input_parameter< List >::type hap_list(hap_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sumstats_beta(sumstats_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sumstats_se(sumstats_seSEXP);
    Rcpp::traits::input_parameter< List >::type precomp(precompSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< bool >::type has_covar(has_covarSEXP);
    Rcpp::traits::input_parameter< bool >::type cond_local(cond_localSEXP);
    Rcpp::traits::input_parameter< int >::type num_ancs(num_ancsSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_chunk_with_sumstats_softfail_linear(dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, has_covar, cond_local, num_ancs));
    return rcpp_result_gen;
END_RCPP
}
// fill_chunk_without_sumstats_linear
List fill_chunk_without_sumstats_linear(List dos_list, List hap_list, IntegerVector idx, List precomp, List control, bool has_covar, bool cond_local, int num_ancs);
RcppExport SEXP _tlstractor_fill_chunk_without_sumstats_linear(SEXP dos_listSEXP, SEXP hap_listSEXP, SEXP idxSEXP, SEXP precompSEXP, SEXP controlSEXP, SEXP has_covarSEXP, SEXP cond_localSEXP, SEXP num_ancsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dos_list(dos_listSEXP);
    Rcpp::traits::input_parameter< List >::type hap_list(hap_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< List >::type precomp(precompSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< bool >::type has_covar(has_covarSEXP);
    Rcpp::traits::input_parameter< bool >::type cond_local(cond_localSEXP);
    Rcpp::traits::input_parameter< int >::type num_ancs(num_ancsSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_chunk_without_sumstats_linear(dos_list, hap_list, idx, precomp, control, has_covar, cond_local, num_ancs));
    return rcpp_result_gen;
END_RCPP
}
// tlstractor_logistic_precompute
List tlstractor_logistic_precompute(NumericVector y, NumericMatrix A, int maxit, double tol, int max_step_halving, double tol_scale_rank);
RcppExport SEXP _tlstractor_tlstractor_logistic_precompute(SEXP ySEXP, SEXP ASEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP max_step_halvingSEXP, SEXP tol_scale_rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_step_halving(max_step_halvingSEXP);
    Rcpp::traits::input_parameter< double >::type tol_scale_rank(tol_scale_rankSEXP);
    rcpp_result_gen = Rcpp::wrap(tlstractor_logistic_precompute(y, A, maxit, tol, max_step_halving, tol_scale_rank));
    return rcpp_result_gen;
END_RCPP
}
// fill_chunk_with_sumstats_softpass_logistic
List fill_chunk_with_sumstats_softpass_logistic(List dos_list, List hap_list, IntegerVector idx, NumericVector sumstats_beta, NumericVector sumstats_se, List precomp, List control, bool cond_local, int num_ancs);
RcppExport SEXP _tlstractor_fill_chunk_with_sumstats_softpass_logistic(SEXP dos_listSEXP, SEXP hap_listSEXP, SEXP idxSEXP, SEXP sumstats_betaSEXP, SEXP sumstats_seSEXP, SEXP precompSEXP, SEXP controlSEXP, SEXP cond_localSEXP, SEXP num_ancsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dos_list(dos_listSEXP);
    Rcpp::traits::input_parameter< List >::type hap_list(hap_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sumstats_beta(sumstats_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sumstats_se(sumstats_seSEXP);
    Rcpp::traits::input_parameter< List >::type precomp(precompSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< bool >::type cond_local(cond_localSEXP);
    Rcpp::traits::input_parameter< int >::type num_ancs(num_ancsSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_chunk_with_sumstats_softpass_logistic(dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, cond_local, num_ancs));
    return rcpp_result_gen;
END_RCPP
}
// fill_chunk_with_sumstats_softfail_logistic
List fill_chunk_with_sumstats_softfail_logistic(List dos_list, List hap_list, IntegerVector idx, NumericVector sumstats_beta, NumericVector sumstats_se, List precomp, List control, bool cond_local, int num_ancs);
RcppExport SEXP _tlstractor_fill_chunk_with_sumstats_softfail_logistic(SEXP dos_listSEXP, SEXP hap_listSEXP, SEXP idxSEXP, SEXP sumstats_betaSEXP, SEXP sumstats_seSEXP, SEXP precompSEXP, SEXP controlSEXP, SEXP cond_localSEXP, SEXP num_ancsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dos_list(dos_listSEXP);
    Rcpp::traits::input_parameter< List >::type hap_list(hap_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sumstats_beta(sumstats_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sumstats_se(sumstats_seSEXP);
    Rcpp::traits::input_parameter< List >::type precomp(precompSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< bool >::type cond_local(cond_localSEXP);
    Rcpp::traits::input_parameter< int >::type num_ancs(num_ancsSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_chunk_with_sumstats_softfail_logistic(dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, cond_local, num_ancs));
    return rcpp_result_gen;
END_RCPP
}
// fill_chunk_without_sumstats_logistic
List fill_chunk_without_sumstats_logistic(List dos_list, List hap_list, IntegerVector idx, List precomp, List control, bool cond_local, int num_ancs);
RcppExport SEXP _tlstractor_fill_chunk_without_sumstats_logistic(SEXP dos_listSEXP, SEXP hap_listSEXP, SEXP idxSEXP, SEXP precompSEXP, SEXP controlSEXP, SEXP cond_localSEXP, SEXP num_ancsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dos_list(dos_listSEXP);
    Rcpp::traits::input_parameter< List >::type hap_list(hap_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< List >::type precomp(precompSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< bool >::type cond_local(cond_localSEXP);
    Rcpp::traits::input_parameter< int >::type num_ancs(num_ancsSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_chunk_without_sumstats_logistic(dos_list, hap_list, idx, precomp, control, cond_local, num_ancs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tlstractor_extract_tracts_flare_cpp", (DL_FUNC) &_tlstractor_extract_tracts_flare_cpp, 6},
    {"_tlstractor_extract_tracts_cpp", (DL_FUNC) &_tlstractor_extract_tracts_cpp, 7},
    {"_tlstractor_convert_tracts_txt_to_gds_cpp", (DL_FUNC) &_tlstractor_convert_tracts_txt_to_gds_cpp, 5},
    {"_tlstractor_gds_to_txt_open_writer_cpp", (DL_FUNC) &_tlstractor_gds_to_txt_open_writer_cpp, 2},
    {"_tlstractor_gds_to_txt_write_header_cpp", (DL_FUNC) &_tlstractor_gds_to_txt_write_header_cpp, 2},
    {"_tlstractor_gds_to_txt_append_chunk_cpp", (DL_FUNC) &_tlstractor_gds_to_txt_append_chunk_cpp, 7},
    {"_tlstractor_gds_to_txt_close_writer_cpp", (DL_FUNC) &_tlstractor_gds_to_txt_close_writer_cpp, 1},
    {"_tlstractor_merge_task_results_cpp", (DL_FUNC) &_tlstractor_merge_task_results_cpp, 4},
    {"_tlstractor_tlstractor_linear_precompute", (DL_FUNC) &_tlstractor_tlstractor_linear_precompute, 3},
    {"_tlstractor_fill_chunk_with_sumstats_softpass_linear", (DL_FUNC) &_tlstractor_fill_chunk_with_sumstats_softpass_linear, 10},
    {"_tlstractor_fill_chunk_with_sumstats_softfail_linear", (DL_FUNC) &_tlstractor_fill_chunk_with_sumstats_softfail_linear, 10},
    {"_tlstractor_fill_chunk_without_sumstats_linear", (DL_FUNC) &_tlstractor_fill_chunk_without_sumstats_linear, 8},
    {"_tlstractor_tlstractor_logistic_precompute", (DL_FUNC) &_tlstractor_tlstractor_logistic_precompute, 6},
    {"_tlstractor_fill_chunk_with_sumstats_softpass_logistic", (DL_FUNC) &_tlstractor_fill_chunk_with_sumstats_softpass_logistic, 9},
    {"_tlstractor_fill_chunk_with_sumstats_softfail_logistic", (DL_FUNC) &_tlstractor_fill_chunk_with_sumstats_softfail_logistic, 9},
    {"_tlstractor_fill_chunk_without_sumstats_logistic", (DL_FUNC) &_tlstractor_fill_chunk_without_sumstats_logistic, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_tlstractor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
