# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extract_tracts_flare_cpp <- function(vcf_path, num_ancs, out_prefix, formats, chunk_size, gds_append_fn) {
    invisible(.Call(`_tlstractor_extract_tracts_flare_cpp`, vcf_path, num_ancs, out_prefix, formats, chunk_size, gds_append_fn))
}

extract_tracts_cpp <- function(vcf_path, msp_path, num_ancs, out_prefix, formats, chunk_size, gds_append_fn) {
    invisible(.Call(`_tlstractor_extract_tracts_cpp`, vcf_path, msp_path, num_ancs, out_prefix, formats, chunk_size, gds_append_fn))
}

convert_tracts_txt_to_gds_cpp <- function(dosage_files, hap_files, nsamples, chunk_size, gds_append_fn) {
    invisible(.Call(`_tlstractor_convert_tracts_txt_to_gds_cpp`, dosage_files, hap_files, nsamples, chunk_size, gds_append_fn))
}

gds_to_txt_open_writer_cpp <- function(out_path, gz) {
    .Call(`_tlstractor_gds_to_txt_open_writer_cpp`, out_path, gz)
}

gds_to_txt_write_header_cpp <- function(writer_ptr, sample_ids) {
    invisible(.Call(`_tlstractor_gds_to_txt_write_header_cpp`, writer_ptr, sample_ids))
}

gds_to_txt_append_chunk_cpp <- function(writer_ptr, chroms, pos, ids, refs, alts, mat) {
    invisible(.Call(`_tlstractor_gds_to_txt_append_chunk_cpp`, writer_ptr, chroms, pos, ids, refs, alts, mat))
}

gds_to_txt_close_writer_cpp <- function(writer_ptr) {
    invisible(.Call(`_tlstractor_gds_to_txt_close_writer_cpp`, writer_ptr))
}

merge_task_results_cpp <- function(output_path, task_file_prefix, task_file_suffix, num_tasks) {
    invisible(.Call(`_tlstractor_merge_task_results_cpp`, output_path, task_file_prefix, task_file_suffix, num_tasks))
}

tlstractor_linear_precompute <- function(y, A, tol_scale_rank = 1.0) {
    .Call(`_tlstractor_tlstractor_linear_precompute`, y, A, tol_scale_rank)
}

fill_chunk_with_sumstats_softpass_linear <- function(dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, has_covar, cond_local, num_ancs) {
    .Call(`_tlstractor_fill_chunk_with_sumstats_softpass_linear`, dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, has_covar, cond_local, num_ancs)
}

fill_chunk_with_sumstats_softfail_linear <- function(dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, has_covar, cond_local, num_ancs) {
    .Call(`_tlstractor_fill_chunk_with_sumstats_softfail_linear`, dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, has_covar, cond_local, num_ancs)
}

fill_chunk_without_sumstats_linear <- function(dos_list, hap_list, idx, precomp, control, has_covar, cond_local, num_ancs) {
    .Call(`_tlstractor_fill_chunk_without_sumstats_linear`, dos_list, hap_list, idx, precomp, control, has_covar, cond_local, num_ancs)
}

tlstractor_logistic_precompute <- function(y, A, maxit = 25L, tol = 1e-8, max_step_halving = 10L, tol_scale_rank = 1.0) {
    .Call(`_tlstractor_tlstractor_logistic_precompute`, y, A, maxit, tol, max_step_halving, tol_scale_rank)
}

fill_chunk_with_sumstats_softpass_logistic <- function(dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, cond_local, num_ancs) {
    .Call(`_tlstractor_fill_chunk_with_sumstats_softpass_logistic`, dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, cond_local, num_ancs)
}

fill_chunk_with_sumstats_softfail_logistic <- function(dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, cond_local, num_ancs) {
    .Call(`_tlstractor_fill_chunk_with_sumstats_softfail_logistic`, dos_list, hap_list, idx, sumstats_beta, sumstats_se, precomp, control, cond_local, num_ancs)
}

fill_chunk_without_sumstats_logistic <- function(dos_list, hap_list, idx, precomp, control, cond_local, num_ancs) {
    .Call(`_tlstractor_fill_chunk_without_sumstats_logistic`, dos_list, hap_list, idx, precomp, control, cond_local, num_ancs)
}

